//
//  OptionsView.swift
//  Wreckpointer
//
//  Created by Danylo Ternovoi on 29.12.2023.
//

import SwiftUI
import WidgetKit

struct OptionsView: View {
    
    @AppStorage("showUnapprovedWrecks",store: UserDefaults(suiteName: "group.com.danyloternovoi.Wreckpointer"))
    var showUnapprovedWrecks: Bool = false
    
    @Binding var showModeratorPage: Bool
    var body: some View {
        NavigationView {
            List {
                VStack(alignment: .leading) {
                    Toggle("Unapproved wrecks", isOn: $showUnapprovedWrecks)
                    Text("This option will show wrecks with unapproved status on map. Unapproved wrecks mostly generated by artificial intelligence and are pending to be moderated.")
                        .font(.caption2)
                        .fontWeight(.light)
                        .foregroundStyle(Color.secondary)
                        .padding(.top, 5)
                    Text("This option may greatly decrease map performance.")
                        .font(.caption2)
                        .fontWeight(.light)
                        .foregroundStyle(Color.accentColor)
                }
                VStack(alignment: .leading) {
                    Toggle("Moderator mode", isOn: $showModeratorPage)
                    Text("This option activates moderator functional. Please note, this functional requires authorization. Contact wreckpointer@gmail.com to get moderator account.")
                        .font(.caption2)
                        .fontWeight(.light)
                        .foregroundStyle(Color.secondary)
                        .padding(.top, 5)
                }
            }
            .navigationTitle("Options")
        }
    }
}

#Preview {
    OptionsView(showModeratorPage: .constant(false))
}
